name: My-website-$(Date:yyyyMMdd).$(Rev:r)

trigger:
  branches:
    include:
      - master

pr: none

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: NodeTool@0
    displayName: 'Install Node.js'
    inputs:
      versionSpec: '12.x'

  - bash: |
      set -ex
      npm ci
      npm run build
    displayName: 'Install & build site'

  - bash: |
      set -ex
      rm -f ./public/*.map
      rm -f ./public/webpack.stats.json
    displayName: 'Remove vulnerabilities'

  - bash: |
      set -ex
      az storage blob upload-batch \
        --account-name $(ACCOUNT_NAME) \
        --account-key $(ACCOUNT_KEY_MASTER) \
        --source ./public/
    displayName: 'Deploy to storage'
